# Generated by Django 6.0.3 on 2026-04-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rebuild_exam_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='twilio', max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='student.examregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
