# Generated by Django 6.0.3 on 2026-04-18 17:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_installment_unique_together_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='courses',
            field=models.ManyToManyField(blank=True, to='student.course'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.center')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.trainer')),
            ],
        ),
    ]
