# Generated by Django 6.0.3 on 2026-04-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_attendance_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerschedule',
            options={'ordering': ['batch__time', 'trainer__name', 'center__name']},
        ),
        migrations.AlterField(
            model_name='trainerschedule',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.center'),
        ),
    ]
