# Generated by Django 6.0.3 on 2026-04-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_trainerschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['time', 'name']},
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
