# Generated by Django 6.0.3 on 2026-04-18 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_trainer_age_trainer_courses_trainer_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
