# Generated by Django 6.0.3 on 2026-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_batch_options_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='certificate_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='certificate_given_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
