# Generated by Django 6.0.3 on 2026-04-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_trainer_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='time_new',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
