# Generated by Django 6.0.3 on 2026-04-24 21:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_examregistration_certificate_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='counsellor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.center'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='joining_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
