# Generated by Django 6.0.3 on 2026-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_batch_time_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='time_new',
        ),
        migrations.AlterField(
            model_name='batch',
            name='time',
            field=models.TimeField(),
        ),
    ]
