# Generated by Django 6.0.3 on 2026-04-24 21:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_counsellor_options_counsellor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alt_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enquiry_date', models.DateField(default=datetime.date.today)),
                ('fee_discussed', models.IntegerField(blank=True, null=True)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_scheduled', 'Demo Scheduled'), ('demo_attended', 'Demo Attended'), ('follow_up', 'Follow-up Pending'), ('ready', 'Ready For Admission'), ('admitted', 'Admitted'), ('lost', 'Lost / Not Interested')], default='new', max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('last_follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_remarks', models.TextField(blank=True, null=True)),
                ('demo_date', models.DateField(blank=True, null=True)),
                ('demo_result', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_probability', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('lost_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('converted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.counsellor')),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.course')),
                ('preferred_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.batch')),
                ('preferred_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.center')),
            ],
            options={
                'ordering': ['-updated_at', '-enquiry_date', 'name'],
            },
        ),
    ]
