# Generated by Django 6.0.3 on 2026-04-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_batch_time_new_alter_batch_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pc', models.PositiveIntegerField(default=0)),
                ('working_pc', models.PositiveIntegerField(default=0)),
                ('repair_pc', models.PositiveIntegerField(default=0)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.center')),
            ],
        ),
    ]
