# Generated by Django 6.0.3 on 2026-04-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_centerlogistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerlogistics',
            name='working_pc',
        ),
    ]
