# Generated by Django 6.0.3 on 2026-04-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
