# Generated by Django 6.0.3 on 2026-04-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('system', 'System')], default='sms', max_length=20)),
                ('category', models.CharField(choices=[('fee_reminder', 'Fee Reminder'), ('enquiry_follow_up', 'Enquiry Follow-up'), ('daily_summary', 'Daily Summary'), ('general', 'General')], default='general', max_length=30)),
                ('recipient_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('provider', models.CharField(default='twilio', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='student.enquiry')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
