# Generated by Django 6.0.3 on 2026-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_trainer_counsellor_user_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='can_send_fee_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_send_follow_up_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
