# Generated by Django 6.0.3 on 2026-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_counsellor_can_send_fee_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='can_access_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_access_enquiries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_access_logistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_access_student_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_access_student_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_convert_enquiries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_edit_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_manage_batches',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_manage_fees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_view_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='record_scope',
            field=models.CharField(choices=[('assigned', 'Only assigned records'), ('center', 'Center records'), ('all', 'All records')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_access_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_access_enquiries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_access_logistics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_access_student_records',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_access_student_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_convert_enquiries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_edit_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_manage_batches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_manage_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_view_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='record_scope',
            field=models.CharField(choices=[('assigned', 'Only assigned records'), ('center', 'Assigned center records'), ('all', 'All records')], default='assigned', max_length=20),
        ),
    ]
